### PR TITLE
Refresh role with force parameter

### PR DESCRIPTION
**Pull request by saurabhjambhule**
This PR addresses https://github.com/jmhale/okta-awscli/issues/122 and https://github.com/jmhale/okta-awscli/issues/125 issues.

This is pretty handy for users having multiple roles assigned to them.
With `--force` parameter, it will now prompt role choice. So that the user need not to manually remove existing role from config file, in case he/she wants to switch role.

### CODE REVIEW

**Comment by thenoid** [comment]
There is already a `--force` option, maybe it's worth renaming it?

**Comment by aggrata** [comment]
This is additional functionality in `--force` parameter. Currently the `--force` parameter only fetches new STS credentials corresponding to the present role in config file. With the refresh role, it will ignore present role and will force to select role again. I believe it's a good way if anyone want to update role in there profile instead of manually editing config file.

**Comment by saurabhjambhule** [comment]
This is additional functionality in `--force` parameter. Currently the `--force` parameter only fetches new STS credentials corresponding to the present role in config file. With the refresh role, it will ignore present role and will force to select role again. I believe it's a good way if anyone want to update role in the profile instead of manually editing config file.

**Comment by ericamador** [comment]
@saurabhjambhule @jonjohnston I see this was approved a while ago. I would find it helpful if this was merged. Is there anything I can do to help facilitate that?

**Review by jmhale — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
