### PR TITLE
Feature/document shorthand flag names

### PR DESCRIPTION
**Pull request by rrhodes**
What?
=====
1. Add shorthand flags for `--okta-profile` (`-o`) and `--profile` (`-p`), and
2. document all shorthand flag names - both new and existing options.

Why?
====
For convenience - it would be nice to have a shorthand for my existing setup using `--profile` and the documentation was missing some existing flags.

### CODE REVIEW

**Comment by rrhodes** [comment]
Hi @jmhale, made some minor modifications around shorthand flags. Mostly adding to the existing documentation. Would you mind reviewing this for me, please?

**Comment by rrhodes** [comment]
Converted this one to a draft until [PR 158](https://github.com/jmhale/okta-awscli/pull/158) is reviewed and approved.

**Comment by jmhale** [comment]
@rrhodes do you want to update this one now that #158 is merged? That way we can get both sets of changes out when I cut `0.5.0`

**Comment by rrhodes** [comment]
Cheers for merging #158, @jmhale! This one should be updated and ready for review again. :)

**Review by jmhale — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
